config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  devise_for :users

  resources :videos do
    resources :comments
    get 'filter', on: :member
    collection do
      post :confirm
    end
  end
  resources :favorites, only: [:index, :create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :video
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :video
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :videos
  has_many :favorites, dependent: :destroy
end

app/models/video.rb
class Video < ApplicationRecord
  validates :title,    length: { in: 1..20 }
  validates :url,      length: { in: 1..400 }
  validates :url,      format: /\A#{URI::regexp(%w(http https))}\z/
  validates :url,      :uniqueness => {:scope => [:user_id], message: 'は既に投稿されたものです'}
  validates :url,      format: { with: /google/, message: 'は「https://drive.google.com」を含んだアドレスにしてください'}
  validates :url,      format: { with: /drive/, message: 'は「https://drive.google.com」を含んだアドレスにしてください' }
  validates :status,   length: { in: 1..11 }
  belongs_to :user
  has_many :comments,  dependent: :destroy
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @video = Video.find(params[:video_id])
    @comment = @video.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.js { render :error }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    #comment投稿したときみたいにindex.js.erbを呼ぶ
      if @comment.destroy
        render 'index'
      end
  end

  private

  def comment_params
    params.require(:comment).permit(:video_id, :content)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites.page(params[:page]).per(6)
  end

  def create
    favorite = current_user.favorites.create(video_id: params[:video_id])
    redirect_to favorites_path, notice: "お気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to favorites_path, notice: "お気に入り解除しました"
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  layout 'index'
  def index
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :show, :new, :edit, :update, :destroy]
  before_action :own_video?, only: [:show, :edit, :update, :destroy]

  def index
    @videos = Video.where(user_id: current_user.id).reverse_order.page(params[:page]).per(6)
  end

  def filter
    if params[:id]
      if params[:id] == "pre"
        @videos = Video.where(user_id: current_user.id).reverse_order.where(status: "準備中").page(params[:page]).per(6)
      elsif params[:id] == "pre_done"
        @videos = Video.where(user_id: current_user.id).reverse_order.where(status: "準備完了").page(params[:page]).per(6)
      elsif params[:id] == "posted"
        @videos = Video.where(user_id: current_user.id).reverse_order.where(status: "Youtube投稿済み").page(params[:page]).per(6)
      end
    else
      @videos = Video.where(user_id: current_user.id).reverse_order.page(params[:page]).per(6)
    end
    render 'index'
  end

  def new
    if params[:back]
      @video = Video.new(video_params)
    else
      @video = Video.new
    end
  end

  def create
    @video = current_user.videos.build(video_params)
    @video.url.sub!(/open\?id=/, "file/d/")
    @video.url << "/preview"
    if @video.save
      PostMailer.post_mail(@video).deliver
      redirect_to videos_path, notice: "ビデオメモを作成しました！"
    else
      render 'new'
    end
  end

  def show
    @comments = @video.comments
    @comment = @video.comments.build
    @favorite = current_user.favorites.find_by(video_id: @video.id)
  end

  def edit
  end

  def update
    if @video.update(video_params)
      redirect_to videos_path, notice: "ビデオメモを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @video.destroy
    params[:id] == "delete"
    redirect_to videos_path, notice:"ビデオメモを削除しました！"
  end

  def confirm
    @video = current_user.videos.build(video_params)
    render :new if @video.invalid?
  end

  private

  def video_params
    params.require(:video).permit(:title, :url, :status, :image, :image_cache)
  end

  def set_video
    @video = Video.find(params[:id])
  end

  def own_video?
    if @video.user_id != current_user.id
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    html = []
    html << content_tag(:div, class: '', role: 'alert') do
      content_tag(:ul) do
        resource.errors.full_messages.each do |error_message|
          concat content_tag(:span, error_message.to_s)
          concat tag(:br)
        end
      end
    end

    safe_join html
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_videos_path
    elsif action_name == 'edit'
      video_path
    end
  end
end

app/views/comments/_form.html.erb
<%= form_with(model: [video, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form_width" id="form_color">
    <div><%= form.label :content, {class: 'control-label'} %></div>
    <div><%= form.text_area :content, {class: 'form-control form_width'} %></div>
    <p id="form_help" style="display:none">※コメントが空です</p>
  </div>

  <div class="actions">
    <%= form.submit "コメントを投稿", :class=>"square_btn" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <% if comment.id.present? %>
    <div class="box8">
      <div><h5><%= comment.content %></h5></div>
      <%= comment.created_at.strftime("%Y-%m-%d %H:%M") %>
      <%= link_to '削除', video_comment_path(video.id, comment.id), remote: true, method: :delete, data: { confirm: '本当に削除していいですか？' }, class: "btn btn-default" %>
    </div>
  <% end %>
<% end %>

app/views/comments/error.js.erb
var element = document.getElementById("form_color");
element.classList.add( "has-error" );
var help = document.getElementById("form_help");
help.style = '';
help.classList.add("help-block");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.video.comments, video: @comment.video }) %>")
$("textarea").val('')
var element = document.getElementById("form_color");
element.classList.remove( "has-error" );
var help = document.getElementById("form_help");
help.style = 'display:none';
help.classList.remove("help-block");

app/views/favorites/index.html.erb
<div class="index">
  <div class="row">
    <div class="center">
      <div class="h2">あなたのお気に入りした投稿</div>
      <% @favorites.each do |favorite| %>
        <div class="col-md-4 col-xs-12">
          <div class="box">
            <div class="box-title">
              <%= favorite.video.status %>
              <iframe src="<%= favorite.video.url %>" width="320" height="240"></iframe>
              <div class="top_bottom">
                <span class="h4"><%= favorite.video.title %></span>
                <div class="float_right">
                  <%= link_to image_tag("show.png", height: 22),video_path(favorite.video.id) %>
                  <%= link_to image_tag("edit.png", height: 22),edit_video_path(favorite.video.id) %>
                  <%= link_to image_tag("delete.png", height: 22), video_path(favorite.video.id), method: :delete, data: { confirm: '本当に削除していいですか？'} %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%= paginate @favorites %>
    <div class="margin_bottom200">
      <p><%= link_to '新しく動画メモを投稿する', new_video_path, class: "btn btn-default", data: {"turbolinks" => false} %></p>
      <p><%= link_to 'ビデオメモ一覧画面にもどる', videos_path, class: "btn btn-default" %></p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag "inside/app", :media => "all" %>
<%= favicon_link_tag 'favicon.png'%>
<html>
  <head>
    <title>VideoManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
        <%= link_to image_tag("logo_small.png", height: 54), root_path %>
        <% if user_signed_in? %>
          <li class: "right_header"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <li class: "right_header"><%= link_to "お気に入り一覧", favorites_path %></li>
          <li class: "right_header"><%= link_to "メモ一覧", videos_path %></li>
          <li class: "right_header"><%= link_to "メモ投稿", new_video_path, data: {"turbolinks" => false} %></li>
        <% else %>
          <li class: "right_header"><%= link_to "ログイン", new_user_session_path, data: {"turbolinks" => false} %></li>
          <li class: "right_header"><%= link_to "新規登録", new_user_registration_path, data: {"turbolinks" => false} %></li>
        <% end %>
      </ul>
    </header>
    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>
    <%= yield %>
    <footer>
      <p>運営会社SATOMAYA</p>
      <p>©︎2018-2019 video memo</p>
    </footer>
  </body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag "inside/app", :media => "all" %>
<html>
  <head>
    <title>VideoManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>
    <%= yield %>
    <footer>
      <p>運営会社SATOMAYA</p>
      <p>©︎2018-2019 video memo</p>
    </footer>
  </body>
</html>

app/views/top/index.html.erb
<%= stylesheet_link_tag "inside/top", :media => "all" %>
<div class="background row center">
  <div class="right">
  </div>
  <div class="">
    <div class="col-md-6"><%= image_tag 'logo_small.png', :size => '600x150' %></div>
    <div class="col-md-6">
      <% if current_user %>
        <%= link_to '動画管理を始める', new_video_path, :class => 'opacity_btn', data: {"turbolinks" => false} %>
        <div><%= link_to "ログアウト", destroy_user_session_path, :method => 'delete', :class => 'square_btn', data: {"turbolinks" => false} %></div>
      <% else %>
        <%= link_to '新規登録をして動画管理を始める', new_user_registration_path, :class => 'opacity_btn', data: {"turbolinks" => false} %>
        <div><%= link_to "ログイン", new_user_session_path, :class => 'square_btn', data: {"turbolinks" => false} %></div>
      <% end %>
    </div>
  </div>
</div>
<div class="main">
  <div class="clear">
    <div class="h1 margin_bottom50"><strong>動画管理</strong>を<strong>スマート</strong>にしよう</div>
    <div class="h4"><span class="pop h2">Youtube Creater's </span>とは</div>
    <div class="h4">Googleドライブと合わせて利用することで</div>
    <div class="h4 margin_bottom50">動画投稿準備の状況管理ができるアプリです</div>
    <div>
      <div class="row">
        <div class="use col-md-4 col-xs-12">
          <%= image_tag 'maiku.png', :size => '150x150', :class => '' %>
          <h5>録音した音源をステータス機能とコメント機能を使って</h5>
          <h5>スマートに管理することができます</h5>
        </div>
        <div class="use col-md-4 col-xs-12">
          <%= image_tag 'sumaho.png', :size => '150x150', :class => '' %>
          <h5>スマートフォン上に音源を保存しておかなくて良いので</h5>
          <h5>携帯の容量を削減できます</h5>
        </div>
        <div class ="use use_bottom col-md-4 col-xs-12">
          <%= image_tag 'youtube.png', :size => '150x150', :class => '' %>
          <h5>アプリ上で再生したり、思ったことをコメントに残しながら</h5>
          <h5>どの動画をUPするかを悩むことができます</h5>
        </div>
      </div>
    </div>
    <div class="margin_bottom200">
      <h4 class="margin_bottom35"><span class="pop h2">Youtube Creater's </span>の使い方</h4>
      <h4 class="back">STEP 1</h4>
      <h4 class="margin_bottom35">録音した動画をGoogleドライブにUP</h4>
      <h4 class="back">STEP 2</h4>
      <h4 class="margin_bottom35">共有可能なリンクを取得する</h4>
      <h4 class="back">STEP 3</h4>
      <h4>タイトル、編集ステータス、GoogleドライブのURLを</h4>
      <h4 class="margin_top5 margin_bottom35">本アプリに投稿し、管理する</h4>
    </div>
  </div>
</div>

app/views/videos/_form.html.erb
<%= stylesheet_link_tag "inside/videos", :media => "all" %>
<%= form_with(model: @video, local: true, url: choose_new_or_edit) do |form| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= @video.errors.count %>件のエラーがあります。</h2>
      <% @video.errors.full_messages.each do |msg| %>
      <span><%= msg %></br></span>
      <% end %>
    </div>
  <% end %>

  <div class="video_title form-group">
    <div class="h3">タイトル</div>
    <%= form.text_field :title, id:"size_1", class: "form-control form_width" %>
  </div>
  <div class="video_url form-group">
    <div class="h3">Googleドライブの動画URL</div>
    <%= form.text_field :url, id:"size_2", class: "form-control form_width" %>
  </div>
  <div class="video_status form-group">
    <div class="h3">ステータス</div>
    <%= form.select "status", [["準備中", "準備中"], ["準備完了", "準備完了"], ["Youtube投稿済み", "Youtube投稿済み"]], {},{:class => "form-control form_width", :id=>"size_3"} %>
  </div>
  <div class="video_status form-group margin_top50">
    <div class="h3">動画編集に使用する画像</div>
    <%= image_tag @video.image, :width => "640" if @video.image %>
    <%= form.file_field :image, class: "form-controll form_width center" %>
  </div>
  <div class="margin_top50">
    <%= form.submit :class=>"square_btn" %>
  </div>
<% end %>
<%= link_to 'ビデオメモ一覧画面にもどる', videos_path, class: "btn btn-default margin_bottom100 margin_top50" %>
<script>
  let screen = window.parent.screen.width;
  let pc = 992;
  if (screen <= pc){
    var size_1 = document.getElementById("size_1");
    if (size_1){
      size_1.classList.remove("form_width");
      size_1.classList.add("xs_size");
    }
    var size_2 = document.getElementById("size_2");
    if (size_2){
      size_2.classList.remove("form_width");
      size_2.classList.add("xs_size");
    }
    var size_3 = document.getElementById("size_3");
    if (size_3){
      size_3.classList.remove("form_width");
      size_3.classList.add("xs_size");
    }
  }
</script>

app/views/videos/_links.html.erb
<div class="margin_top50 margin_bottom50">
  <% @AllClass = "sample btn" %>
  <% @PreClass = "sample btn" %>
  <% @Pre_doneClass = "sample btn" %>
  <% @PostedClass = "sample btn" %>
  <% if params[:id] == "pre" %>
    <% @PreClass = "sample_select btn" %>
  <% elsif params[:id] == "pre_done" %>
    <% @Pre_doneClass = "sample_select btn" %>
  <% elsif params[:id] == "posted" %>
    <% @PostedClass = "sample_select btn" %>
  <% else %>
    <% @AllClass = "sample_select btn" %>
  <% end %>
  <%= link_to 'ALL', videos_path, class: @AllClass %>
  <%= link_to '準備中', filter_video_path('pre'), class: @PreClass %>
  <%= link_to '準備完了', filter_video_path('pre_done'), class: @Pre_doneClass %>
  <%= link_to 'Youtube投稿済み', filter_video_path('posted'), class: @PostedClass %>
</div>

app/views/videos/confirm.html.erb
<%= stylesheet_link_tag "inside/videos", :media => "all" %>
<div class="center">
  <h3>以下の内容で、送信する。</h3>

  <%= form_with(model: @video, url: videos_path, local: true) do |form| %>
    <%= form.hidden_field :title %>
    <%= form.hidden_field :url %>
    <%= form.hidden_field :status %>
    <%= form.hidden_field :image_cache %>

    <div class="margin_bottom200">
      <div class="margin_top50 margin_bottpm50"><h4>タイトル:</h4><%= @video.title %></div>
      <% url = @video.url %>
      <% url.sub!(/open\?id=/, "file/d/") %>
      <% url << "/preview" %>
      <div class="margin_bottom50"><iframe src="<%= url %>" width="320" height="240" ></iframe><div>
      <div class="margin_bottom50"><h4>ステータス:</h4><%= @video.status %></div>
      <% if @video.image.url %>
        <div>
          <div class="margin_bottom50"><h4>動画編集に使用する画像:</h4>
            <%= image_tag @video.image, :width => "640" %>
          </div>
        </div>
      <% end %>
    </div>
  <div class="margin_top50">
    <%= form.submit :class=>"square_btn" %>
  </div>
  <% end %>

  <%= form_with(model: @video, url: new_video_path, local: true, method: 'get') do |form| %>
    <%= form.hidden_field :title %>
    <%= form.hidden_field :url %>
    <%= form.hidden_field :status %>
    <%= form.submit "もどる", name: 'back', :class=>"btn btn-default margin_top50", data: {"turbolinks" => false} %>
  <% end %>
</div>

app/views/videos/edit.html.erb
<div class="index">
  <div class="margin_bottom50">
    <h2>ビデオメモを編集する</h2>
  </div>
  <%= render 'form' %>
</div>

app/views/videos/index.html.erb
<%= stylesheet_link_tag "inside/videos", :media => "all" %>
<div class="index">
  <div class="row">
    <h1>動画一覧</h1>
    <%= render partial: 'videos/links', locals: { video: @video } %>
    <% @videos.each do |video| %>
      <div class="col-md-4 col-xs-12">
        <div class="box">
          <div class="box-title">
            <%= video.status %>
            <iframe src="<%= video.url %>" width="320" height="240"></iframe>
            <div class="top_bottom">
              <h5><%= video.title %></h5>
              <span class="h6"><%= video.created_at.strftime("%Y-%m-%d %H:%M") %></span>
              <div class="float_right">
                <%= link_to image_tag("show.png", height: 22),video_path(video.id) %>
                <%= link_to image_tag("edit.png", height: 22),edit_video_path(video.id) %>
                <%= link_to image_tag("delete.png", height: 22), video_path(video.id), method: :delete, data: { confirm: '本当に削除していいですか？'} %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @videos %>
  <div class="new_botan">
    <%= link_to '新しく動画メモを投稿する', new_video_path, class: "btn btn-default", data: {"turbolinks" => false} %>
  </div>
</div>

app/views/videos/new.html.erb
<div class="index">
  <div class="margin_bottom50">
    <h2>ビデオメモを作成する</h2>
  </div>
  <%= render 'form' %>
</div>

app/views/videos/show.html.erb
<div class="center">
  <div class="margin_bottom50">
    <h1>ビデオメモ詳細画面</h1>
  </div>
  <div class="show">
    <div class="margin_bottom50">
      <h4>タイトル</h4><%= @video.title %>
    </div>
    <div class="margin_bottom50">
      <h4>投稿日時</h4><%= @video.created_at.strftime("%Y-%m-%d %H:%M") %>
    </div>
    <div class="margin_bottom50">
      <h4>ステータス</h4><%= @video.status %>
    </div>
    <div><iframe src="<%= @video.url %>" width="640" height="480"></iframe><div>
    <% if @video.image.url %>
      <div class="margin_bottom50">
        <div><h4>動画編集に使用する画像:</h4>
          <%= image_tag @video.image, :width => "640" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="margin_top50">
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(video_id: @video.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div class="margin_top50">
    <h2>コメント一覧</h2>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, video: @video } %>
    </div>
  </div>
  <%= render partial: 'comments/form', locals: { comment: @comment, video: @video } %>
  <div class="padding-20px margin_bottom50 margin_top50">
    <%= link_to '編集', edit_video_path(@video), class: "btn btn-default" %> |
    <%= link_to '戻る', videos_path, class: "btn btn-default" %>
  </div>
  <div class="margin_bottom200">
    <p><%= link_to '新しく動画メモを投稿する', new_video_path, class: "btn btn-default", data: {"turbolinks" => false} %></p>
  </div>
</div>